# This script is the first thing sourced by the initramfs script.
# Just spin for now so we can tell when we get the kernel started successfully.
while true; do
    sleep 1
done

sdcard_partition=mmcblk0p36
