#@TYPE: Machine
#@NAME: Samsung Galaxy Watch 4/FE kernel
#@DESCRIPTION: Machine configuration for the Samsung Galaxy Watch 4/FE kernel

# Exynos s5e5515 SoC uses Cortex A55 cores
require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc
DEFAULTTUNE = "cortexa55"

# Use the modified Android vendor kernel
PREFERRED_PROVIDER_virtual/kernel = "linux-lucky7"
PREFERRED_VERSION_linux = "5.15+tiramisu"
KERNEL_IMAGETYPE = "Image"
