#@TYPE: Machine
#@NAME: Samsung Galaxy Watch 4/FE
#@DESCRIPTION: Machine configuration for the Samsung Galaxy Watch 4/FE

require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc
DEFAULTTUNE = "cortexa55"
require conf/machine/include/hybris-watch.inc

# Don't generate a sparse image.
# These watches do not have Fastboot, the entire partition must be flashed.
GENERATE_SPARSE_IMAGE = "false"

MACHINE_DISPLAY_ROUND = "true"
MACHINE_HAS_WLAN = "true"

PREFERRED_VERSION_android = "u"
PREFERRED_PROVIDER_virtual/kernel = "linux-lucky7"
PREFERRED_VERSION_linux = "5.15+t"

IMAGE_INSTALL += "sensorfw-hybris-hal-plugins android-tools android-system underclock msm-fb-refresher asteroid-compass"
