#@TYPE: Machine
#@NAME: lucky7 
#@DESCRIPTION: Machine configuration for the Samsung Galaxy Watch FE (SM-R861/SM-R866), running the mainline Linux kernel.

# Exynos5515 SoC uses Cortex A55 cores
require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc
DEFAULTTUNE = "cortexa55"

MACHINE_FEATURES = ""

PREFERRED_PROVIDER_virtual/mesa ?= "mesa"
PREFERRED_PROVIDER_virtual/egl ?= "mesa"
PREFERRED_PROVIDER_virtual/libgl ?= "mesa"
PREFERRED_PROVIDER_virtual/libgbm ?= "mesa"
PREFERRED_PROVIDER_virtual/gles ?= "mesa"
PREFERRED_PROVIDER_virtual/libgles1 ?= "mesa"
PREFERRED_PROVIDER_virtual/libgles2 ?= "mesa"

MACHINE_DISPLAY_ROUND = "true"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS:append = " mesa "

PREFERRED_PROVIDER_virtual/kernel = "linux-lucky7"
KERNEL_IMAGETYPE = "Image"
KERNEL_DEVICETREE = "exynos/exynos5515-lucky7.dtb"

MKBOOTIMG_HEADER_VERSION = "4"
MKBOOTIMG_VENDOR_BOOT = "true"
MKBOOTIMG_INIT_BOOT = "true"
MKBOOTIMG_DTBO = "true"
MKBOOTIMG_DT_ARGS = "--custom1=255"
MKBOOTIMG_DTBO_ARGS = "--custom1=32"
