BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"
BBFILES += "${LAYERDIR}/recipes*/*/*/*.bb ${LAYERDIR}/recipes*/*/*/*.bbappend"
BBFILE_COLLECTIONS += "lucky7-layer"
BBFILE_PATTERN_lucky7-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_lucky7-layer = "8"
LAYERSERIES_COMPAT_lucky7-layer = "walnascar"
